
run: "260204-above1e7"

scenarios: ["vanilla"]#"fossil50+nowind","fossil50","nowind","vanilla"]

point_list: "population_by_coord.csv"
threshold: 1.2e6


octant_folder: "../octants/"
defaults_file: "defaults.csv"
tech_years_default: 2030
tech_years: [2020, 2030, 2040, 2050]
