
run: "260215-maxcost"

scenarios: ["maxcost100+vol2000"]#"solarwindbatt100","solarwindbatt100+battcost20","solarwindbatt100+battcost50","solarbatt100","solarbatt100+battcost20","solarbatt100+battcost50"]#,"solarwindbatt95","solarwindbatt99"]#,"solarbatt90"]#"fossil50+nowind","fossil50","nowind","vanilla"]
#scenarios: ["solarbatt90","solarbatt95","solarbatt99"]#,"solarbatt90"]#"fossil50+nowind","fossil50","nowind","vanilla"]

lon_step: 1
lat_step: 1

point_list: "population_by_coord.csv"
threshold: 3.2e5


octant_folder: "../octants/"
defaults_file: "defaults.csv"
tech_years_default: 2050
tech_years: [2020, 2030, 2040, 2050]
