
value_start: 50
value_stop: 151
value_step: 50

lon_step: 10
lat_step: 10

octant_folder: "../octants/"
defaults_file: "elasticity/defaults.csv"
tech_years_default: 2030
tech_years: [2020, 2030, 2040, 2050]
