
run: "260202-tech2050"

scenarios: ["fossil50+nowind","fossil50","nowind","vanilla"]

lon_step: 10
lat_step: 10

octant_folder: "../octants/"
defaults_file: "defaults.csv"
tech_years_default: 2050
tech_years: [2020, 2030, 2040, 2050]
