
run: "260206-solarbatt2050"

scenarios: ["solarbatt99","solarbatt95"]#,"solarbatt90"]#"fossil50+nowind","fossil50","nowind","vanilla"]

point_list: "population_by_coord.csv"
threshold: 1e6


octant_folder: "../octants/"
defaults_file: "defaults.csv"
tech_years_default: 2050
tech_years: [2020, 2030, 2040, 2050]
